server:
  port: 8080
  servlet:
    #session会话超时时间
    session:
      timeout: 60
    # 应用的访问路径
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    context-path: /tale_blog
spring:
  mvc:
    static-path-pattern: /static/**
  # 多环境配置
  profiles:
    active: @profile.active@
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # 格式化JSON日期
  jackson:
   time-zone: GMT+8
   date-format: yyyy-MM-dd HH:mm:ss
   default-property-inclusion: always
  # jpa配置
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
     ddl-auto: update
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
     hibernate:
      temp:
       use_jdbc_metadata_defaults: false
      dialect: org.hibernate.dialect.MySQL5Dialect
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc
    #初始化表结构.初次使用的时候会在库中生成表格,后期注释掉即可.或者初始使用值为always,然后将值改为never
    jdbc:
      initialize-schema: never
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
##############################################
#
# thymeleaf静态资源配置
#
##############################################
thymeleaf:
  # 默认路径
  prefix: classpath:/templates/
  # 后缀
  suffix: .html
  # 模版样式
  mode: HTML5
  encoding: UTF-8
  cache: false
  servlet:
    content-type: text/html
security:
  oauth2:
    resource:
      filter-order: 3
# 日志配置
logging:
   level:
     io.github: debug
     org.springframework: warn