spring:
  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&nullCatalogMeansCurrent=true&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    #监控统计拦截的filters
    filters: stat,wall,log4j
    #druid配置
    #配置初始化大小/最小/最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    #获取连接等待超时时间
    maxWait: 60000
    #间隔多久进行一次检测，检测需要关闭的空闲连接
    timeBetweenEvictionRunsMillis: 60000
    #一个连接在池中最小生存的时间
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties:
      druid:
        stat:
          mergeSql: true
          slowSqlMillis: 5000
  # redis配置
  redis:
    ssl: false
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1000
    password:
    lettuce:
      pool:
        max-active: 100
        max-wait: -1
        min-idle: 0
        max-idle: 20
aliyun:
  oss:
    endPoint: oss-cn-beijing.aliyuncs.com
    url: https://platform-application.oss-cn-beijing.aliyuncs.com/
    accessKeyId: xxx
    accessKeySecret: xxx
    bucketName: xxx
  sms:
    accessKeyId: xxx
    accessKeySecret: xxx
    signName: xxx
  mail:
    accessKeyId: xxx #邮件服务 accessKeyId
    accessKeySecret: xxx #邮件服务 accessKeySecret
    accountName: xxx #邮件服务 发信地址
    regionId: cn-hangzhou #邮件服务 区域Id
    sendPersonName: xxx #邮件服务 发信人昵称(程序无法正常读取中文，若是中文应写到程序中)
    addressType: 1 #邮件服务  取值范围 0~1: 0 为随机账号；1 为发信地址
    tagName: xxx #邮件服务 控制台创建的标签
    replyToAddress: false #邮件服务 回信地址
    toAddress:  #邮件服务  目标地址