server:
  port: 8080
  servlet:
    #session会话超时时间
    session:
      timeout: PT5H
    # 应用的访问路径
    context-path: /
  tomcat:
    uri-encoding: UTF-8
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  autoconfigure:
    #自动化配置 例外处理
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure,org.activiti.spring.boot.SecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  mvc:
    favicon:
      enabled: false
    static-path-pattern: /static/**
  # 多环境配置
  profiles:
    active: @profile.active@
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # 格式化JSON日期
  jackson:
   time-zone: GMT+8
   date-format: yyyy-MM-dd hh:mm:ss
   default-property-inclusion: always
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc
    #初始化表结构.初次使用的时候会在库中生成表格,后期注释掉即可.或者初始使用值为always,然后将值改为never
    jdbc:
      initialize-schema: never
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  # act 是否自动创建表
  activiti:
    database-schema-update: false
    check-process-definitions: false
    process-definition-location-prefix: classpath:/processes/
    history-level: full
##############################################
#
# thymeleaf静态资源配置
#
##############################################
  thymeleaf:
    # 默认路径
    prefix: classpath:/templates/
    # 后缀
    suffix: .html
    # 模版样式
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
##############################################
#
# mybatis-plus 配置
#
##############################################
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: io.github.yangyouwang.crud.**.entity
  global-config:
    # 逻辑删除配置
    db-config:
      # 全局逻辑删除的实体字段名
      logic-delete-field: deleted
      # 删除前
      logic-not-delete-value: 0
      # 删除后
      logic-delete-value: 1
##############################################
#
# 分页插件
#
##############################################
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
##############################################
#
# 日志配置
#
##############################################
logging:
   level:
     io.github: debug
     org.springframework: warn